aliyun:
  accessKeyId: LTAI4Fr5gfYhcVjLMqeRGbuT
  accessKeySecret: IrkcHu6dZyrjPZRushgO76P5392HJ1
  oss:
    bucket: cskaoyan
    endPoint: oss-cn-beijing.aliyuncs.com
  sms:
    signName: stone4j
    templateCode: SMS_173765187
